x-common-config: &common-config
  platform: linux/amd64
  logging:
    driver: "json-file"
    options:
      max-size: "100k"
      max-file: "5"
      
services:
  bitcoin-data:
    <<: *common-config
    image: ghcr.io/argonprotocol/argon-commander-deploy/bitcoin-data:latest
    build: 
      context: data
      dockerfile: Dockerfile
      args:
        - TAR_PATHS=blocks chainstate indexes
      additional_contexts:
        - data=$BITCOIN_DATA_FOLDER
    volumes:
      - $BITCOIN_DATA_FOLDER:/data
    profiles:
      - data
  argon-data:
    <<: *common-config
    image: ghcr.io/argonprotocol/argon-commander-deploy/argon-data:latest
    build: 
      context: data
      dockerfile: Dockerfile
      args:
        - TAR_PATHS=chains/argon/db
      additional_contexts:
        - data=$ARGON_DATA_FOLDER
    volumes:
      - $ARGON_DATA_FOLDER:/data
    profiles:
      - data

  bitcoin:
    <<: *common-config
    image: ghcr.io/argonprotocol/argon-commander-deploy/bitcoin:latest
    restart: unless-stopped
    build: 
      context: bitcoin
      dockerfile: dockerfile
    volumes:
      - $BITCOIN_DATA_FOLDER:/data
  argon-miner:
    <<: *common-config
    image: ghcr.io/argonprotocol/argon-miner:latest
    # TODO this doesnt actually work on linux. It sets this to empty, which also does the trick.
    # Does this mean root user is set?
    user: "${UID}:${GID}"
    restart: unless-stopped
    depends_on:
      - bitcoin
    command: 
      - --bitcoin-rpc-url=http://bitcoin:bitcoin@bitcoin:5000
      - --no-mdns
      - --no-telemetry
      - --port=30333
      - --sync=full
      - --network-backend=libp2p
      - --validator
      - --notebook-archive-hosts=https://notebook-archives.argon.network
      - --chain=mainnet
      - --detailed-log-output
      - --name=argon-miner
      - --state-pruning=256
      - -linfo,pallet=trace,argon=trace,txpool=trace
      - --node-key-file=/data/p2p.key
      - --unsafe-force-node-key-generation
      - --compute-author=5Dts3Cjxb6MphAD9ZP3Q4woaoCeyH9uaGTSHvqDruPPHjtRg
    volumes:
      - $ARGON_DATA_FOLDER:/data
    ports:
     - 30333:30333
