x-common-config: &common-config
  platform: linux/amd64
  logging:
    driver: "json-file"
    options:
      max-size: "100k"
      max-file: "5"
      
services:
  bitcoin-data:
    <<: *common-config
    image: ghcr.io/argonprotocol/argon-commander-deploy/bitcoin-data:latest
    build: 
      context: data
      dockerfile: Dockerfile
      args:
        - TAR_PATHS=blocks chainstate indexes
      additional_contexts:
        - data=$BITCOIN_DATA_FOLDER
    volumes:
      - $BITCOIN_DATA_FOLDER:/data
    profiles:
      - data
  
  bitcoin:
    <<: *common-config
    image: ghcr.io/argonprotocol/argon-commander-deploy/bitcoin:latest
    restart: unless-stopped
    build: 
      context: bitcoin
      dockerfile: Dockerfile
    command:
      - /usr/local/bin/bitcoind
      - -conf=${BITCOIN_CONFIG}
    volumes:
      - $BITCOIN_DATA_FOLDER:/data

  argon-miner:
    <<: *common-config
    build:
      context: ./argon-miner
      dockerfile: Dockerfile
    # TODO this doesnt actually work on linux. It sets this to empty, which also does the trick.
    # Does this mean root user is set?
    user: "${UID}:${GID}"
    restart: unless-stopped
    depends_on:
      - bitcoin
    command: 
      - --bitcoin-rpc-url=http://bitcoin:bitcoin@bitcoin:5000
      - --no-mdns
      - --no-telemetry
      - --port=30333
      - --rpc-port=9944
      - --sync=full
      - --network-backend=libp2p
      - --validator
      - --notebook-archive-hosts=${NOTEBOOK_ARCHIVE_HOSTS}
      - --chain=${ARGON_CHAIN}
      - --detailed-log-output
      - --name=argon-miner
      - --state-pruning=256
      - -linfo,pallet=trace,argon=trace,txpool=trace
      - --node-key-file=/data/p2p.key
      - --unsafe-force-node-key-generation
      - --compute-miners=0
      - --base-path=/argon-data
    volumes:
      - $ARGON_DATA_FOLDER:/argon-data
    ports:
     - 30333:30333
