x-common-config: &common-config
  platform: linux/amd64
  logging:
    driver: "json-file"
    options:
      max-size: "100k"
      max-file: "5"
  networks:
    - default

services:
  bitcoin-data:
    <<: *common-config
    image: ghcr.io/argonprotocol/commander-deploy/bitcoin-data:latest
    build:
      context: data
      dockerfile: Dockerfile
      args:
        - TAR_PATHS=blocks chainstate indexes
      additional_contexts:
        - data=$BITCOIN_DATA_FOLDER
    volumes:
      - $BITCOIN_DATA_FOLDER:/data
    profiles:
      - data
    deploy:
      replicas: 1

  bitcoin:
    <<: *common-config
    image: ghcr.io/argonprotocol/commander-deploy/bitcoin:latest
    restart: unless-stopped
    build:
      context: bitcoin
      dockerfile: Dockerfile
    command:
      - /usr/local/bin/bitcoind
      - -conf=${BITCOIN_CONFIG}
    environment:
      - BITCOIN_CONFIG=${BITCOIN_CONFIG}
      - BITCOIN_CHAIN=${BITCOIN_CHAIN}
    volumes:
      - $BITCOIN_DATA_FOLDER:/data

  argon-miner:
    <<: *common-config
    build:
      context: ./argon-miner
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    restart: unless-stopped
    depends_on:
      - bitcoin
    command:
      - --bitcoin-rpc-url=http://bitcoin:bitcoin@bitcoin:5000
      - --base-path=/data
      - --no-mdns
      - --no-telemetry
      - --port=30333
      - --rpc-port=9944
      - --rpc-methods=unsafe
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --sync=fast
      - --network-backend=libp2p
      - --validator
      - --notebook-archive-hosts=${NOTEBOOK_ARCHIVE_HOSTS}
      - --chain=${ARGON_CHAIN}
      - --detailed-log-output
      - --name=argon-miner
      - --state-pruning=256
      - -linfo,pallet=trace,argon=trace,txpool=trace,argon_notary_apis=info
      - --node-key-file=/data/p2p.key
      - --unsafe-force-node-key-generation
      - --compute-miners=0
    ports:
      - "30333:30333"
      - "9944:9944"
    environment:
      - ARGON_CHAIN=${ARGON_CHAIN}
      - ARGON_ARCHIVE_NODE=${ARGON_ARCHIVE_NODE}
    volumes:
      - $ARGON_DATA_FOLDER:/data

  bot:
    <<: *common-config
    image: ghcr.io/argonprotocol/commander-bot:latest
    restart: unless-stopped
    depends_on:
      - argon-miner
    ports:
      - "3000:3000"
    env_file:
      - ../commander-config/.env.state
      - ../commander-config/.env.security
    environment:
      - PORT=3000
      - BIDDING_RULES_PATH=/tmp/biddingRules.json
      - KEYPAIR_PATH=/tmp/wallet.json
      - LOCAL_RPC_URL=ws://argon-miner:9944
      - ARCHIVE_NODE_URL=${ARGON_ARCHIVE_NODE}
      - DATADIR=/data
    volumes:
      - ../commander-config/wallet.json:/tmp/wallet.json
      - ../commander-config/biddingRules.json:/tmp/biddingRules.json
      - ../commander-config/bidding-calculator/src:/usr/src/app/bidding-calculator/src
      - ../commander-config/bot/src:/usr/src/app/bot/src
      - ../commander-data:/data
    profiles:
      - bot

networks:
  default:
    driver: bridge
